package com.marko.auralis.model

data class AudioDiagnostics(
    val outputDevice: String = "Not active",
    val selectedSampleRate: Int = 0,
    val channelCount: Int = 2,
    val pcmFormat: String = "PCM_FLOAT",
    val requestedPulseUs: Int = 55,
    val actualPulseUs: Double = 0.0,
    val samplesPerPulse: Int = 0,
    val requestedRandomLeftDelayMs: Int = 30,
    val requestedRandomRightDelayMs: Int = 30,
    val actualRandomLeftDelayMs: Double = 0.0,
    val actualRandomRightDelayMs: Double = 0.0,
    val bufferFrames: Int = 0,
    val underrunCount: Int = 0,
    val lowLatencyRequested: Boolean = false,
    val nativeRateHint: Int = 0,
    val cpuUsagePercent: Double = 0.0,
    val memoryUsageMb: Double = 0.0,
    val audioRouteType: Int = 0,
    val safetyOutputGain: Float = 1.0f,
    val focusOutputGain: Float = 1.0f,
    val activeLayers: List<String> = listOf("Pulse"),
    val mixPeak: Float = 0f,
    val protectiveMixGain: Float = 1f,
    val breathingCycleSeconds: Double? = null,
    val binauralLeftHz: Double? = null,
    val binauralRightHz: Double? = null,
    val monauralBeatHz: Double? = null,
    val isochronicRateHz: Double? = null,
    val requestedItdUs: Int? = null,
    val actualItdUs: Double? = null
)
