package com.marko.auralis.model

/** Read-only built-in preset metadata. The installable fallback additionally stores Breath/Noise/Nature layer settings not yet represented by SoundLayerConfig in the Compose model. */
data class BuiltInPresetDefinition(val id:String,val category:String,val evidence:String,val suggestedMinutes:Int,val headphones:String,val nameEn:String,val nameDe:String,val nameHr:String,val subtitleEn:String,val subtitleDe:String,val subtitleHr:String,val config:AudioConfig=AudioConfig(),val layers:SoundLayerConfig=SoundLayerConfig())

object BuiltInPresetCatalog {
    val all=listOf(
        BuiltInPresetDefinition(id="focused_calm",category="focus",evidence="emerging",suggestedMinutes=25,headphones="optional",nameEn="Focused Calm",nameDe="Ruhiger Fokus",nameHr="Mirna koncentracija",subtitleEn="Stable ambient sound with a mild 10 Hz monaural beat.",subtitleDe="Stabile Ambient-Fläche mit mildem 10-Hz-Monaural-Beat.",subtitleHr="Stabilan ambijent uz blagi monauralni beat od 10 Hz.",config=AudioConfig(),layers=SoundLayerConfig(ambientEnabled=true,monauralEnabled=true,ambientBrightness=42,ambientMovement=10,ambientDensity=35,ambientLevel=9,monauralDepth=35,monauralLevel=6,monauralCarrierHz=200.0,monauralBeatHz=10.0)),
        BuiltInPresetDefinition(id="deep_work",category="focus",evidence="experimental",suggestedMinutes=40,headphones="optional",nameEn="Deep Work",nameDe="Tiefes Arbeiten",nameHr="Duboki rad",subtitleEn="Low-information brown noise and a very mild rhythmic layer.",subtitleDe="Informationsarmes Brown Noise mit sehr milder Rhythmuskomponente.",subtitleHr="Brown noise s malo informacija i vrlo blagim ritmičkim slojem.",config=AudioConfig(),layers=SoundLayerConfig(ambientEnabled=true,monauralEnabled=true,ambientBrightness=32,ambientMovement=5,ambientDensity=25,ambientLevel=5,monauralDepth=25,monauralLevel=4,monauralCarrierHz=200.0,monauralBeatHz=9.0)),
        BuiltInPresetDefinition(id="reading_focus",category="focus",evidence="emerging",suggestedMinutes=30,headphones="optional",nameEn="Reading Focus",nameDe="Lesefokus",nameHr="Fokus za čitanje",subtitleEn="Pink noise only, without pulses or spatial motion.",subtitleDe="Nur Pink Noise, ohne Impulse oder räumliche Bewegung.",subtitleHr="Samo pink noise, bez impulsa i prostornog kretanja.",config=AudioConfig(),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="analytical_focus",category="focus",evidence="emerging",suggestedMinutes=25,headphones="optional",nameEn="Analytical Focus",nameDe="Analytischer Fokus",nameHr="Analitički fokus",subtitleEn="220/228 Hz monaural beating under a restrained ambient bed.",subtitleDe="220/228-Hz-Monaural-Beat unter einer zurückhaltenden Ambient-Fläche.",subtitleHr="Monauralni 220/228 Hz beat ispod suzdržane ambijentalne podloge.",config=AudioConfig(),layers=SoundLayerConfig(ambientEnabled=true,monauralEnabled=true,ambientBrightness=45,ambientMovement=5,ambientDensity=30,ambientLevel=6,monauralDepth=50,monauralLevel=7,monauralCarrierHz=220.0,monauralBeatHz=8.0)),
        BuiltInPresetDefinition(id="distraction_mask",category="focus",evidence="emerging",suggestedMinutes=30,headphones="optional",nameEn="Distraction Mask",nameDe="Ablenkungsmaske",nameHr="Maskiranje smetnji",subtitleEn="Steady pink noise for masking irregular environmental sounds.",subtitleDe="Stetiges Pink Noise zum Maskieren unregelmäßiger Umgebungsgeräusche.",subtitleHr="Stabilan pink noise za maskiranje nepravilnih zvukova iz okoline.",config=AudioConfig(),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="light_attention",category="focus",evidence="experimental",suggestedMinutes=20,headphones="optional",nameEn="Light Attention",nameDe="Leichte Aufmerksamkeit",nameHr="Lagana pažnja",subtitleEn="Sparse 3-pulse/s events over a quiet ambient background.",subtitleDe="Sparsame 3-Impulse/s über ruhigem Ambient-Hintergrund.",subtitleHr="Rijetki impulsi 3/s preko tihe ambijentalne podloge.",config=AudioConfig(pulseRateHz=3.0f,requestedPulseUs=55,randomDynamicsPercent=5,randomTimingPercent=5),layers=SoundLayerConfig(ambientEnabled=true,ambientBrightness=40,ambientMovement=5,ambientDensity=25,ambientLevel=5)),
        BuiltInPresetDefinition(id="calm",category="relax",evidence="supported",suggestedMinutes=15,headphones="optional",nameEn="Calm",nameDe="Ruhe",nameHr="Smirenje",subtitleEn="Procedural rain with very slow, shallow stereo movement.",subtitleDe="Prozeduraler Regen mit sehr langsamer, flacher Stereobewegung.",subtitleHr="Proceduralna kiša s vrlo sporim i blagim stereo kretanjem.",config=AudioConfig(),layers=SoundLayerConfig(smoothMotionEnabled=true,motionCycleSeconds=18,motionDepth=18,motionLevel=4)),
        BuiltInPresetDefinition(id="deep_relax",category="relax",evidence="supported",suggestedMinutes=12,headphones="optional",nameEn="Deep Relax",nameDe="Tiefe Entspannung",nameHr="Duboko opuštanje",subtitleEn="4/6 slow breathing with a soft rain background.",subtitleDe="Langsames 4/6-Atmen mit sanftem Regen.",subtitleHr="Sporo 4/6 disanje uz tihu kišu.",config=AudioConfig(),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="after_work",category="relax",evidence="supported",suggestedMinutes=20,headphones="optional",nameEn="After Work",nameDe="Nach der Arbeit",nameHr="Nakon posla",subtitleEn="Ocean texture and slow spatial drift for decompression after sustained work.",subtitleDe="Meeresklang und langsame Raumbewegung zum Herunterfahren nach längerer Arbeit.",subtitleHr="Zvuk oceana i sporo prostorno kretanje za prijelaz nakon duljeg rada.",config=AudioConfig(),layers=SoundLayerConfig(ambientEnabled=true,smoothMotionEnabled=true,ambientBrightness=30,ambientMovement=12,ambientDensity=28,ambientLevel=6,motionCycleSeconds=18,motionDepth=18,motionLevel=4)),
        BuiltInPresetDefinition(id="mental_reset",category="relax",evidence="experimental",suggestedMinutes=12,headphones="optional",nameEn="Mental Reset",nameDe="Mentaler Reset",nameHr="Mentalni reset",subtitleEn="A stream bed with sparse 1.8-pulse/s transients and mild variability.",subtitleDe="Bachklang mit sparsamen 1,8-Impuls/s und leichter Variabilität.",subtitleHr="Žubor potoka uz rijetke impulse 1,8/s i blagu varijabilnost.",config=AudioConfig(pulseRateHz=1.8f,requestedPulseUs=55,randomDynamicsPercent=10,randomTimingPercent=10),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="quiet_room",category="relax",evidence="supported",suggestedMinutes=20,headphones="optional",nameEn="Quiet Room",nameDe="Ruhiger Raum",nameHr="Tiha soba",subtitleEn="Very low pink noise plus rain for a stable neutral acoustic room.",subtitleDe="Sehr leises Pink Noise plus Regen für einen stabilen neutralen Klangraum.",subtitleHr="Vrlo tihi pink noise i kiša za stabilno neutralno zvučno okruženje.",config=AudioConfig(),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="evening_wind_down",category="relax",evidence="supported",suggestedMinutes=25,headphones="optional",nameEn="Evening Wind-Down",nameDe="Abendliches Herunterfahren",nameHr="Večernje smirivanje",subtitleEn="Low-brightness wind and ambient layers without discrete beats.",subtitleDe="Dunkler Wind- und Ambient-Klang ohne diskrete Beats.",subtitleHr="Tamniji zvuk vjetra i ambijenta bez diskretnih beatova.",config=AudioConfig(),layers=SoundLayerConfig(ambientEnabled=true,ambientBrightness=24,ambientMovement=8,ambientDensity=28,ambientLevel=5)),
        BuiltInPresetDefinition(id="cardiac_calm_breathing",category="breathing",evidence="supported",suggestedMinutes=10,headphones="optional",nameEn="Cardiorespiratory Calm Breathing",nameDe="Kardiorespiratorisch ruhiges Atmen",nameHr="Kardiorespiratorno mirno disanje",subtitleEn="4 s inhale / 6 s exhale with a very quiet stream background.",subtitleDe="4 s Einatmen / 6 s Ausatmen mit sehr leisem Bachklang.",subtitleHr="4 s udah / 6 s izdah uz vrlo tihi zvuk potoka.",config=AudioConfig(),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="hrv_breathing_46",category="breathing",evidence="supported",suggestedMinutes=10,headphones="optional",nameEn="HRV-Oriented Breathing 4/6",nameDe="HRV-orientiertes Atmen 4/6",nameHr="HRV-orijentirano disanje 4/6",subtitleEn="A minimal 10-second breathing cycle without extra sound layers.",subtitleDe="Minimaler 10-Sekunden-Atemzyklus ohne zusätzliche Klangschichten.",subtitleHr="Minimalni 10-sekundni ciklus disanja bez dodatnih zvučnih slojeva.",config=AudioConfig(),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="balanced_breathing_55",category="breathing",evidence="supported",suggestedMinutes=10,headphones="optional",nameEn="Balanced Breathing 5/5",nameDe="Ausgeglichenes Atmen 5/5",nameHr="Uravnoteženo disanje 5/5",subtitleEn="Symmetric five-second inhale and five-second exhale.",subtitleDe="Symmetrisch fünf Sekunden ein- und fünf Sekunden ausatmen.",subtitleHr="Simetričnih pet sekundi udaha i pet sekundi izdaha.",config=AudioConfig(),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="long_exhale",category="breathing",evidence="supported",suggestedMinutes=8,headphones="optional",nameEn="Long Exhale",nameDe="Lange Ausatmung",nameHr="Dugi izdah",subtitleEn="Comfortable 4-second inhale followed by a longer 7-second exhale.",subtitleDe="Bequeme 4-Sekunden-Einatmung mit längerer 7-Sekunden-Ausatmung.",subtitleHr="Ugodan udah od 4 sekunde i dulji izdah od 7 sekundi.",config=AudioConfig(),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="respiratory_ease",category="breathing",evidence="supported",suggestedMinutes=10,headphones="optional",nameEn="Respiratory Ease",nameDe="Ruhiges Atemgefühl",nameHr="Lakoća disanja",subtitleEn="4/6 breathing paced against an ocean-like envelope.",subtitleDe="4/6-Atmung vor einer meeresähnlichen Klanghülle.",subtitleHr="4/6 disanje uz zvučnu ovojnicu nalik oceanu.",config=AudioConfig(),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="humming_breath",category="breathing",evidence="emerging",suggestedMinutes=8,headphones="optional",nameEn="Humming Breath",nameDe="Summ-Atem",nameHr="Humming disanje",subtitleEn="Four-second silent inhale and six-second humming exhale guide.",subtitleDe="Vier Sekunden still einatmen und sechs Sekunden summend ausatmen.",subtitleHr="Četiri sekunde tihog udaha i šest sekundi izdaha uz pjevušenje.",config=AudioConfig(),layers=SoundLayerConfig(alternativeLevel=5,alternativeMode=AlternativeMode.HUMMING)),
        BuiltInPresetDefinition(id="sleep_preparation",category="sleep",evidence="emerging",suggestedMinutes=30,headphones="optional",nameEn="Sleep Preparation",nameDe="Schlafvorbereitung",nameHr="Priprema za spavanje",subtitleEn="Low pink noise and ocean texture without pulses or beats.",subtitleDe="Leises Pink Noise und Meeresklang ohne Impulse oder Beats.",subtitleHr="Tihi pink noise i ocean bez impulsa ili beatova.",config=AudioConfig(),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="deep_night",category="sleep",evidence="experimental",suggestedMinutes=30,headphones="optional",nameEn="Deep Night",nameDe="Tiefe Nacht",nameHr="Duboka noć",subtitleEn="Low brown noise with a dark, nearly static ambient bed.",subtitleDe="Leises Brown Noise mit dunkler, nahezu statischer Ambient-Fläche.",subtitleHr="Tihi brown noise uz tamnu, gotovo statičnu ambijentalnu podlogu.",config=AudioConfig(),layers=SoundLayerConfig(ambientEnabled=true,ambientBrightness=15,ambientMovement=4,ambientDensity=20,ambientLevel=4)),
        BuiltInPresetDefinition(id="rain_at_night",category="sleep",evidence="emerging",suggestedMinutes=35,headphones="optional",nameEn="Rain at Night",nameDe="Regen bei Nacht",nameHr="Noćna kiša",subtitleEn="Stable procedural rain with no beat or click layer.",subtitleDe="Stabiler prozeduraler Regen ohne Beat- oder Klickschicht.",subtitleHr="Stabilna proceduralna kiša bez beata ili klikova.",config=AudioConfig(),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="ocean_night",category="sleep",evidence="emerging",suggestedMinutes=35,headphones="optional",nameEn="Ocean Night",nameDe="Meeresnacht",nameHr="Noćni ocean",subtitleEn="Slow ocean-like amplitude movement without discrete rhythm.",subtitleDe="Langsame meeresartige Pegelbewegung ohne diskreten Rhythmus.",subtitleHr="Sporo oceansko gibanje glasnoće bez diskretnog ritma.",config=AudioConfig(),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="slow_breath_before_sleep",category="sleep",evidence="supported",suggestedMinutes=10,headphones="optional",nameEn="Slow Breath Before Sleep",nameDe="Langsames Atmen vor dem Schlaf",nameHr="Sporo disanje prije spavanja",subtitleEn="4/6 breathing over very low pink noise.",subtitleDe="4/6-Atmung über sehr leisem Pink Noise.",subtitleHr="4/6 disanje preko vrlo tihog pink noisea.",config=AudioConfig(),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="minimal_night",category="sleep",evidence="emerging",suggestedMinutes=30,headphones="optional",nameEn="Minimal Night",nameDe="Minimale Nacht",nameHr="Minimalna noć",subtitleEn="Only very low pink noise: no beats, pulses or motion.",subtitleDe="Nur sehr leises Pink Noise: keine Beats, Impulse oder Bewegung.",subtitleHr="Samo vrlo tihi pink noise: bez beatova, impulsa i kretanja.",config=AudioConfig(),layers=SoundLayerConfig()),
        BuiltInPresetDefinition(id="spatial_calm",category="spatial",evidence="experimental",suggestedMinutes=15,headphones="recommended",nameEn="Spatial Calm",nameDe="Räumliche Ruhe",nameHr="Prostorno smirenje",subtitleEn="Low-depth stereo motion through a restrained ambient field.",subtitleDe="Flache Stereobewegung durch eine zurückhaltende Ambient-Fläche.",subtitleHr="Blago stereo kretanje kroz suzdržanu ambijentalnu podlogu.",config=AudioConfig(),layers=SoundLayerConfig(ambientEnabled=true,smoothMotionEnabled=true,ambientBrightness=35,ambientMovement=15,ambientDensity=30,ambientLevel=7,motionCycleSeconds=18,motionDepth=25,motionLevel=5)),
        BuiltInPresetDefinition(id="left_right_flow",category="spatial",evidence="experimental",suggestedMinutes=15,headphones="recommended",nameEn="Left–Right Flow",nameDe="Links–Rechts-Fluss",nameHr="Lijevo–desno tok",subtitleEn="A stream layer that moves gradually left to right and back.",subtitleDe="Bachklang, der sich langsam von links nach rechts und zurück bewegt.",subtitleHr="Zvuk potoka koji se postupno kreće lijevo-desno i natrag.",config=AudioConfig(),layers=SoundLayerConfig(smoothMotionEnabled=true,motionCycleSeconds=10,motionDepth=35,motionLevel=6)),
        BuiltInPresetDefinition(id="bilateral_slow",category="spatial",evidence="experimental",suggestedMinutes=12,headphones="recommended",nameEn="Bilateral Slow",nameDe="Langsam bilateral",nameHr="Sporo bilateralno",subtitleEn="Soft alternating left/right audio at approximately 0.7 alternations per second.",subtitleDe="Weiche Links/Rechts-Wechsel mit ungefähr 0,7 Wechseln pro Sekunde.",subtitleHr="Mekana lijevo/desno izmjena približno 0,7 puta u sekundi.",config=AudioConfig(),layers=SoundLayerConfig(ambientEnabled=true,bilateralEnabled=true,ambientBrightness=30,ambientMovement=0,ambientDensity=25,ambientLevel=5,bilateralSoftness=90,bilateralLevel=5,bilateralRateHz=0.7)),
        BuiltInPresetDefinition(id="spatial_itd_lab",category="spatial",evidence="research",suggestedMinutes=10,headphones="required",nameEn="Spatial ITD Lab",nameDe="Räumliches ITD-Labor",nameHr="Spatial ITD Lab",subtitleEn="A 400 µs left-leading interaural delay for localization exploration.",subtitleDe="400 µs linksführende interaurale Verzögerung zur Lokalisations-Exploration.",subtitleHr="Interauralno kašnjenje 400 µs s vodećim lijevim kanalom za istraživanje lokalizacije.",config=AudioConfig(),layers=SoundLayerConfig(itdEnabled=true,itdUs=400,itdLevel=5)),
        BuiltInPresetDefinition(id="binaural_6",category="beats",evidence="emerging",suggestedMinutes=15,headphones="required",nameEn="Binaural 6 Hz Exploration",nameDe="Binaural 6 Hz",nameHr="Binauralno 6 Hz",subtitleEn="200 Hz left / 206 Hz right; the 6 Hz difference is binaurally perceived.",subtitleDe="200 Hz links / 206 Hz rechts; die 6-Hz-Differenz wird binaural wahrgenommen.",subtitleHr="200 Hz lijevo / 206 Hz desno; razlika 6 Hz percipira se binauralno.",config=AudioConfig(),layers=SoundLayerConfig(binauralEnabled=true,binauralLevel=7,binauralCarrierHz=200.0,binauralBeatHz=6.0)),
        BuiltInPresetDefinition(id="binaural_10",category="beats",evidence="emerging",suggestedMinutes=15,headphones="required",nameEn="Binaural 10 Hz Exploration",nameDe="Binaural 10 Hz",nameHr="Binauralno 10 Hz",subtitleEn="200 Hz left / 210 Hz right for a 10 Hz binaural difference.",subtitleDe="200 Hz links / 210 Hz rechts für eine binaurale 10-Hz-Differenz.",subtitleHr="200 Hz lijevo / 210 Hz desno za binauralnu razliku 10 Hz.",config=AudioConfig(),layers=SoundLayerConfig(binauralEnabled=true,binauralLevel=7,binauralCarrierHz=200.0,binauralBeatHz=10.0)),
        BuiltInPresetDefinition(id="monaural_6",category="beats",evidence="emerging",suggestedMinutes=15,headphones="optional",nameEn="Monaural 6 Hz",nameDe="Monaural 6 Hz",nameHr="Monauralno 6 Hz",subtitleEn="Physical 200/206 Hz acoustic beating present in both channels.",subtitleDe="Physischer 200/206-Hz-Akustikbeat in beiden Kanälen.",subtitleHr="Fizički akustički beat 200/206 Hz prisutan u oba kanala.",config=AudioConfig(),layers=SoundLayerConfig(monauralEnabled=true,monauralDepth=60,monauralLevel=7,monauralCarrierHz=200.0,monauralBeatHz=6.0)),
        BuiltInPresetDefinition(id="soft_iso_6",category="beats",evidence="experimental",suggestedMinutes=12,headphones="optional",nameEn="Soft Isochronic 6 Hz",nameDe="Sanft isochron 6 Hz",nameHr="Meki isochronic 6 Hz",subtitleEn="220 Hz carrier with smooth 6 Hz amplitude modulation.",subtitleDe="220-Hz-Träger mit weicher 6-Hz-Amplitudenmodulation.",subtitleHr="Nosioc 220 Hz s glatkom amplitudnom modulacijom 6 Hz.",config=AudioConfig(),layers=SoundLayerConfig(isochronicEnabled=true,isochronicDepth=45,isochronicSoftness=95,isochronicLevel=7,isochronicCarrierHz=220.0,isochronicRateHz=6.0)),
        BuiltInPresetDefinition(id="ambient_432",category="experimental",evidence="experimental",suggestedMinutes=12,headphones="optional",nameEn="432 Ambient",nameDe="432 Ambient",nameHr="432 Ambient",subtitleEn="Ambient harmonic system referenced to A4=432 Hz.",subtitleDe="Harmonisches Ambient-System mit A4=432 Hz als Stimmreferenz.",subtitleHr="Ambijentalni harmonički sustav s referencom A4=432 Hz.",config=AudioConfig(),layers=SoundLayerConfig(alternativeLevel=7,alternativeMode=AlternativeMode.AMBIENT_432)),
        BuiltInPresetDefinition(id="resonance_528",category="experimental",evidence="experimental",suggestedMinutes=10,headphones="optional",nameEn="528 Resonance",nameDe="528 Resonanz",nameHr="528 Rezonanca",subtitleEn="Harmonic texture centered on 528 Hz rather than a loud bare sine.",subtitleDe="Harmonische Textur um 528 Hz statt eines lauten reinen Sinus.",subtitleHr="Harmonička tekstura centrirana na 528 Hz umjesto glasnog čistog sinusa.",config=AudioConfig(),layers=SoundLayerConfig(alternativeLevel=7,alternativeMode=AlternativeMode.HARMONIC_528)),
        BuiltInPresetDefinition(id="resonant_bowl",category="experimental",evidence="emerging",suggestedMinutes=12,headphones="optional",nameEn="Resonant Bowl",nameDe="Resonanzschale",nameHr="Rezonantna zdjela",subtitleEn="Synthetic bowl with several inharmonic resonant partials and slow decay.",subtitleDe="Synthetische Schale mit mehreren inharmonischen Resonanzen und langsamem Abklingen.",subtitleHr="Sintetička zdjela s više neharmoničnih rezonanci i sporim raspadom.",config=AudioConfig(),layers=SoundLayerConfig(alternativeLevel=8,alternativeMode=AlternativeMode.BOWL)),
        BuiltInPresetDefinition(id="sound_bath",category="experimental",evidence="emerging",suggestedMinutes=15,headphones="optional",nameEn="Sound Bath",nameDe="Sound Bath",nameHr="Sound Bath",subtitleEn="Slow bowl/gong-like procedural resonances with low event density.",subtitleDe="Langsame schalen-/gongartige prozedurale Resonanzen mit geringer Ereignisdichte.",subtitleHr="Spore proceduralne rezonance nalik zdjelama/gongu s malom gustoćom događaja.",config=AudioConfig(),layers=SoundLayerConfig(alternativeLevel=8,alternativeMode=AlternativeMode.SOUND_BATH)),
        BuiltInPresetDefinition(id="schumann_783",category="experimental",evidence="traditional",suggestedMinutes=10,headphones="optional",nameEn="7.83 Hz Schumann-Inspired",nameDe="7,83 Hz Schumann-inspiriert",nameHr="7,83 Hz Schumann-inspired",subtitleEn="Audible carrier amplitude-modulated at 7.83 Hz; not an electromagnetic Schumann field.",subtitleDe="Hörbarer Träger mit 7,83-Hz-Amplitudenmodulation; kein elektromagnetisches Schumann-Feld.",subtitleHr="Čujni nosioc amplitudno moduliran na 7,83 Hz; nije elektromagnetsko Schumannovo polje.",config=AudioConfig(),layers=SoundLayerConfig(alternativeLevel=6,alternativeMode=AlternativeMode.MOD_783)),
        BuiltInPresetDefinition(id="solfeggio_528",category="experimental",evidence="traditional",suggestedMinutes=10,headphones="optional",nameEn="Solfeggio 528",nameDe="Solfeggio 528",nameHr="Solfeggio 528",subtitleEn="Controlled 528 Hz member of the modern Solfeggio frequency set.",subtitleDe="Kontrollierter 528-Hz-Ton aus dem modernen Solfeggio-Frequenzsatz.",subtitleHr="Kontrolirani ton 528 Hz iz modernog Solfeggio skupa frekvencija.",config=AudioConfig(),layers=SoundLayerConfig(solfeggioHz=528,alternativeLevel=6,alternativeMode=AlternativeMode.SOLFEGGIO)),
        BuiltInPresetDefinition(id="solfeggio_396",category="experimental",evidence="traditional",suggestedMinutes=10,headphones="optional",nameEn="Solfeggio 396",nameDe="Solfeggio 396",nameHr="Solfeggio 396",subtitleEn="Controlled 396 Hz member of the modern Solfeggio frequency set.",subtitleDe="Kontrollierter 396-Hz-Ton aus dem modernen Solfeggio-Frequenzsatz.",subtitleHr="Kontrolirani ton 396 Hz iz modernog Solfeggio skupa frekvencija.",config=AudioConfig(),layers=SoundLayerConfig(solfeggioHz=396,alternativeLevel=6,alternativeMode=AlternativeMode.SOLFEGGIO)),
        BuiltInPresetDefinition(id="forest_reset",category="relax",evidence="emerging",suggestedMinutes=20,headphones="optional",nameEn="Forest Reset",nameDe="Wald-Reset",nameHr="Šumski reset",subtitleEn="Procedural forest ambience with barely perceptible slow stereo movement.",subtitleDe="Prozeduraler Waldklang mit kaum merklicher langsamer Stereobewegung.",subtitleHr="Proceduralni šumski ambijent s jedva primjetnim sporim stereo kretanjem.",config=AudioConfig(),layers=SoundLayerConfig(smoothMotionEnabled=true,motionCycleSeconds=18,motionDepth=15,motionLevel=4))
    )
}
